### ISSUE TITLE
start configuration button is greyed.

### ISSUE THREAD

**Issue by tomspeed22** [solidify/scale#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tomspeed22** [comment]
When starting @Scale in Azure Devops the "Start Configuration" is greyed out. Hence I cannot start configuring @Scale in my project. Can you help to unlock the start configuration button ? Thanks

**Comment by MOlausson** [comment]
@tomspeed22 the button is enabled if 1) you are the one created the Scale subscription or 2) you are in the project collection administrators group. If you want we can follow up off-line if you reach out to us at scale@solidify.dev.
