### ISSUE TITLE
Dark Theme Display not displaying correctly on Board

### ISSUE THREAD

**Issue by kristow** [solidify/scale#14]
We are leveraging @scale extension with Azure DevOps Sever (Version 18.181.31626.1 ).  One of the recent updates introduced a bug for users running in Dark Mode.  On the Boards tab of @Scale the first column is a white background in Dark Mode See screenshot below for example.

![2022-10-10 11_27_33-@Scale - Board and 14 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/16941835/194912699-aad0bb66-2570-42e9-8569-c52a5de1cf0a.png)

**Comment by JimmyKB** [comment]
This has been fixed with the latest release v1.4.111

Thanks for reporting! We appreciate it
