### ISSUE TITLE
Process configuration error

### ISSUE THREAD

**Issue by Tienst** [solidify/scale#19]
**Describe the bug**
Error when trying to configure the @Scale extension for a project. 

**To Reproduce**
1. Go to Azure DevOps project named AgilePractices
2. Click on @Scale extension under Boards
3. Click on 'Start configuration'
4. Use the default setup settings, click on "Next"
5. In the Configuration summary page, go with the default settings, click on "Save"
6. Receive an error message " Error creating work item types" and can't proceed further.
7. The SAFe process template is created with Agile Release Train, PI Objective and Program Increment work types, but not Risk work item type.

**Expected behavior**
That the process template and work item types would be created and configuration would move to step 3.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 108.0.1462.46

![AtScaleConfigurationError](https://user-images.githubusercontent.com/75448831/206931064-24148596-563a-4dd2-9851-38ea5cddf92b.jpg)

**Comment by JimmyKB** [comment]
@Tienst Hello!

Thank you for reporting, Can you try with our latest version v1.5.15? You can see the version number when clicking "?" in the bottom right of scale

Please verify that it works and I will close this ticket

**Comment by Tienst** [comment]
It worked, thank you!
