### ISSUE TITLE
Dependencies still showing after Collapse all of teams.

### ISSUE THREAD

**Issue by SNBMikeGemmell** [solidify/scale#20]
**Describe the bug**
Dependencies on the program board are still shown if you do a "collapse all" of the teams.

**To Reproduce**
1. Given an ART, with multiple teams and some items on the @Scale board.
2. Turn on show dependencies via the settings.
3. Create dependencies between items.
4. Now use the Collapse all in the team column.
5. Notice how the dependencies are still shown without connecting anything.  See attached screenshot.

**Expected behavior**
I would expect the dependencies to disappear when you "Collapse all" the teams.  Dependencies are hidden when teams are collapsed individually. 

**Screenshots**
![image](https://user-images.githubusercontent.com/119605010/207058615-8323fd2a-b0e6-46e2-8183-14c8ef9bcf99.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10 (21H2)
 - Browser Microsoft Edge (107.0.1418.62)
 - @Scale version 1.5.11

**Additional context**
N/A

**Comment by JimmyKB** [comment]
Thank you for reporting! We're investing the issue further

**Comment by JimmyKB** [comment]
Hello @SNBMikeGemmell. This got fixed in our latest release v1.5.38. 
Once again, thank you for reporting.
