### ISSUE TITLE
Unable to specify some state values in WSJF board query

### ISSUE THREAD

**Issue by ehilfer** [solidify/scale#21]
**Describe the bug**
Some state values are not showing in the value dropdown when creating query in WSJF Board.
When selecting a comparison operator like "In" I am unable to type in values or to select multiple values form the dropdown list.

**To Reproduce**
**Problem 1:**
Open WSJF Board
Click +New Query
In first query clause, select "State" under the Field selection
Select "=" from the operator dropdown
Try to select "Analyzing" from the "Value" dropdown (this is a custom state we have on features) - the "Analyzing" state is not in the dropdown, and I am unable to type it in free-form.

**Problem 2:**
Open WSJF Board
Click +New Query
In first query clause, select "State" under the Field selection
Select "In" from the operator dropdown
Try to indicate multiple values in the "Value" dropdown - it isn't [possible, and I am unable to type in a free-form list of values to match against

**Expected behavior**
I except to find all State values, including custom state values, for all workitem types available for match, or to have the ability to type in a known state value.
I expect to be able to specify multiple state values in the value field for multi=-value comparison operators like ?In".  Whether by multi-selecting from a list or typing in a list by hand.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - BrowserChrome
 - Version 107.0.5304.110 (Official Build) (arm64)]

**Comment by JimmyKB** [comment]
Thank you for reporting, we are investigating the issue further and i'll come back to you if we need any more information. I'll leave this ticket open until it's solved

**Comment by JimmyKB** [comment]
Hello @ehilfer,
I'm sorry that this has taken a while to solve.

We've now released an update for WSJF queries that should solve all of your issues. 
Thank you for reporting.
