### ISSUE TITLE
Groups enabled for License Management for @Scale.

### ISSUE THREAD

**Issue by kristow** [solidify/scale#24]
**Is your feature request related to a problem? Please describe.**
It is a manual effort to add and remove individual users to @Scale license. 

**Describe the solution you'd like**
Enable the ability to use ADO groups and Active Directory groups to manage who has a license. 

**Describe alternatives you've considered**
Creating external automation for this.

**Comment by JimmyKB** [comment]
Hello Kristow, This is an ongoign question as this would require us to to do more on the client side that we do today. We have an upcoming feature that will allow CSV import and Export, But adding AD-groups/entre ID is not on the agenda for now.
