### ISSUE TITLE
Objectives are randomly sorted in list

### ISSUE THREAD

**Issue by alfnilsson** [solidify/scale#26]
**Describe the bug**
The items in the Objectives list is not consistently sorted.

**To Reproduce**
1. Go to 'Objectives'
2. Open the Objectives for a team that has many items, note what order the items are listed
3. Open an Objective
4. Close the Objective
5. The sort order of the items has changed

**Expected behavior**
The sort order is the same as before I opened the Objective.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 114.0.1823.106 

**Additional context**

**Comment by JimmyKB** [comment]
Thank you for reporting @alfnilsson We are investigating the issue and will get back you if we need more details. We will close this issue once it has been resolved.

**Comment by JimmyKB** [comment]
Latest release solves this issue
