### ISSUE TITLE
@Scale plugin bad readability on dark theme

### ISSUE THREAD

**Issue by bobinush** [solidify/scale#30]
**Describe the bug**
Work item number and titles sometimes not visible since the background is too bright.
Summary of number of work items when collapsed and dependencies in/out are not visible since the background is too bright.
Q: Why are some work items background super bright?
I have tried:
- cleared cache
- switched to light theme in Devops and back to dark again

**To Reproduce**
Have multiple teams and dependencies between features, have features planned out in sprints.
1. Go to @Scale
2. Click on Board
3. Click on Collapse All

**Expected behavior**
Being able to see work item number and title of all tickets, circled in the smaller red box.
Being able to see the text on mini-cards that I think refers to dependencies and how many tickets (when collapsed), circled in the bigger red box.

**Screenshots**
![image](https://github.com/solidify/scale/assets/12391559/cf30547c-783d-44db-ae20-107d2f7b454d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version 121.0.6167.185

**Comment by JimmyKB** [comment]
Hello @bobinush, Thanks for reporting.

Do you have a custom color set by styling in your board settings?

**Comment by bobinush** [comment]
Is that a setting in the extension on organizational level? Because I personally do not have access to those settings, but I can ask around in my company.

**Comment by bobinush** [comment]
I personally dont have access to that setting, I will check with someone who has and get back to you!

**Comment by bobinush** [comment]
Looks like we did have custom color set, thank you for the suggestion.

But the "mini cards" that is only visible when a teams swim lane is collapsed is still white on white. Is that something also changed with the style setting?

**Comment by bobinush** [comment]
Bump!
I am referring to these "mini cards" 
![image](https://github.com/solidify/scale/assets/12391559/98b66da2-1022-4d71-931d-cad73c4deff3)

**Comment by JimmyKB** [comment]
Hello @bobinush, Sorry for the delay. We will fix this ASAP, it's currently planned work.

Please use our support email in the future for immediate answers
support.scale@solidify.dev

**Comment by JimmyKB** [comment]
@bobinush
Good news, Just giving you an update. We have it planned to release on Monday.

In the future, please email support.scale@solidify.dev so I can have a clear conscience, There we respond much quicker
